language: ruby
rvm:
  - 1.8.7
before_script:
  - "git clone git://github.com/puppetlabs/puppet-apt.git spec/fixtures/modules/apt && git clone git://github.com/puppetlabs/puppetlabs-stdlib.git spec/fixtures/modules/stdlib && git clone git://github.com/puppetlabs/puppetlabs-mysql.git spec/fixtures/modules/mysql && git clone git://github.com/ripienaar/puppet-concat.git spec/fixtures/modules/concat"
after_script:
script: "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=2.7.6
  - PUPPET_VERSION=2.6.9
notifications:
  email: false
